# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Build and deploy Jekyll site to GitHub Pages

on:
  # ðŸ’Ž Runs on pushes targeting the default branch
  push:
    branches:
      - eQ19
      - Chetabahana

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions: write-all

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“‚ Checkout
        uses: actions/checkout@v3

      - name: ðŸ”¨ Get gem cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          restore-keys: |
            ${{ runner.os }}-gems-
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}

      - name: ðŸš€ Build and deploy
        uses: MarketLeader/Packages@v1
        with:
          bundler_ver: '2.3.7'
          pre_build_commands: 'make build'
          token: ${{ secrets.JEKYLL_GITHUB_TOKEN }}
